-- Fix Course uuid values that were generated by md5() (32-char hex without dashes)
-- Replace them with proper UUID v4 values using PostgreSQL's gen_random_uuid()
UPDATE "Course"
SET "uuid" = gen_random_uuid()::text
WHERE "uuid" IS NOT NULL AND "uuid" NOT LIKE '________-____-____-____-____________';
